# Generated by Django 3.2 on 2021-05-22 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='block_days', to='listings.bookinginfo')),
            ],
        ),
    ]
