# Generated by Django 3.2 on 2021-05-22 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_blockday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockday',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_days', to='listings.bookinginfo'),
        ),
    ]
